name: Generate version number from push

on: 
  push:
    branches:
      - main
      - UAT
      - develop

permissions:
  contents: write        

jobs:
  generate-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{env.fullversion}}
    steps:
      - uses: actions/checkout@v4
        id: checkout
        with:
          fetch-tags: true
          fetch-depth: 0

      ### DECISION 1 ### is previous tag found?
      - id: get-tag
        name: Get latest semantic version tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        with: 
          semver_only: true
          
      ### DECISION 2 ### is commit a merged PR?
      - id: get-PR
        name: Get merged pull request
        ## DECISION 1 RESULT ## yes
        if: steps.get-tag.outputs.tag != '' 
        uses: actions-ecosystem/action-get-merged-pull-request@v1
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}

      ### DECISION 3 ### was PR labelled?
      - id: get-PR-level
        name: Get release tag from PR
        ## DECISION 2 RESULT ## yes
        if: steps.get-PR.outputs.number != null
        uses: actions-ecosystem/action-release-label@v1
        with: 
          label_prefix: release/
          labels: ${{steps.get-PR.outputs.labels}}    

        ## DECISION 3 RESULT ## yes
      - if: ${{ steps.get-PR-level.outputs.level != null }}
        name: Push level to env
        run: echo "releaselevel=${{steps.get-PR-level.outputs.level}}" >> $GITHUB_ENV

      
        ## DECISION 3 RESULT ## no
      - if: ${{ steps.get-PR-level.outputs.level == null }}
        name: Push default level to env
        run: echo "releaselevel=patch" >> $GITHUB_ENV

      - uses: actions-ecosystem/action-bump-semver@v1
        ## DECISION 1 RESULT ## yes
        if: steps.get-tag.outputs.tag != ''
        id: bump-semver
        name: Bump semantic version
        with:
          current_version: ${{ steps.get-tag.outputs.tag }}
          level: ${{env.releaselevel}}
      
      - id: semver-to-env
        ## DECISION 1 RESULT ## yes
        if: steps.get-tag.outputs.tag != ''
        name: Push bumped version to env
        run: echo "nextversion=${{steps.bump-semver.outputs.new_version}}" >> $GITHUB_ENV
          
      - id: default
        name: No tag default version num to env
        ## DECISION 1 RESULT ## no 
        if: steps.get-tag.outputs.tag == ''
        run: echo "nextversion=1.0.0" >> $GITHUB_ENV

      - name: Push version to repo tags
        if: github.event.ref == 'refs/heads/main'
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ env.nextversion }}

      - name: Truncate hash
        id: trunc-hash
        run: |
          hash="${{github.event.after}}"
          echo "hash=${hash:0:7}" >> $GITHUB_OUTPUT
          
      - name: Get branch name
        shell: bash
        run: echo "branch=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
        id: get-branch

      - name: Add -preprod+hash
        if: steps.get-branch.outputs.branch == 'main'
        run: echo "fullversion=${{ env.nextversion }}-preprod+${{steps.trunc-hash.outputs.hash}}" >> $GITHUB_ENV
       
      - name: Add -branchname+hash
        if: steps.get-branch.outputs.branch != 'main'
        run: echo "fullversion=${{ env.nextversion }}-${{steps.get-branch.outputs.branch}}+${{steps.trunc-hash.outputs.hash}}" >> $GITHUB_ENV
        
  print-version:
    runs-on: ubuntu-latest
    needs: generate-version
    steps:
      - run: echo ${{needs.generate-version.outputs.version}}

